test_set = [
    {"question": "What were the Legal Professionals revenues in Q3 2025?", "answer": "728"},
    {"question": "What were the Corporates revenues in Q3 2025?", "answer": "478"},
    {"question": "What were the Tax & Accounting Professionals revenues in Q3 2025?", "answer": "251"},
    {"question": "What were the Big 3 revenues in Q3 2025?", "answer": "1,457"},
    {"question": "What was the total revenue growth for Legal Professionals in Q3 2025?", "answer": "-2%"},
    {"question": "What was the constant currency growth for Legal Professionals in Q3 2025?", "answer": "-2%"},
    {"question": "What was the organic revenue growth for Legal Professionals in Q3 2025?", "answer": "+9%"},
    {"question": "What was the total revenue growth for Corporates in Q3 2025?", "answer": "+10%"},
    {"question": "What was the constant currency growth for Corporates in Q3 2025?", "answer": "+9%"},
    {"question": "What was the organic revenue growth for Corporates in Q3 2025?", "answer": "+9%"},
    {"question": "What was the total revenue growth for Tax & Accounting Professionals in Q3 2025?", "answer": "+13%"},
    {"question": "What was the constant currency growth for Tax & Accounting Professionals in Q3 2025?", "answer": "+15%"},
    {"question": "What was the organic revenue growth for Tax & Accounting Professionals in Q3 2025?", "answer": "+10%"},
    {"question": "What was the total revenue growth for the Big 3 in Q3 2025?", "answer": "+4%"},
    {"question": "What was the constant currency growth for the Big 3 in Q3 2025?", "answer": "+4%"},
    {"question": "What was the organic revenue growth for the Big 3 in Q3 2025?", "answer": "+9%"},
    {"question": "What were the Legal Professionals revenues for the nine months 2025?", "answer": "2,130"},
    {"question": "What were the Corporates revenues for the nine months 2025?", "answer": "1,491"},
    {"question": "What were the Tax & Accounting Professionals revenues for the nine months 2025?", "answer": "888"},
    {"question": "What were the Big 3 revenues for the nine months 2025?", "answer": "4,509"},
    {"question": "What was the total revenue growth for Legal Professionals for the nine months 2025?", "answer": "-3%"},
    {"question": "What was the constant currency growth for Legal Professionals for the nine months 2025?", "answer": "-3%"},
    {"question": "What was the organic revenue growth for Legal Professionals for the nine months 2025?", "answer": "+8%"},
    {"question": "What was the total revenue growth for Corporates for the nine months 2025?", "answer": "+8%"},
    {"question": "What was the constant currency growth for Corporates for the nine months 2025?", "answer": "+8%"},
    {"question": "What was the organic revenue growth for Corporates for the nine months 2025?", "answer": "+9%"},
    {"question": "What was the total revenue growth for Tax & Accounting Professionals for the nine months 2025?", "answer": "+11%"},
    {"question": "What was the constant currency growth for Tax & Accounting Professionals for the nine months 2025?", "answer": "+13%"},
    {"question": "What was the organic revenue growth for Tax & Accounting Professionals for the nine months 2025?", "answer": "+11%"},
    {"question": "What was the total revenue growth for the Big 3 for the nine months 2025?", "answer": "+3%"},
    {"question": "What was the constant currency growth for the Big 3 for the nine months 2025?", "answer": "+3%"},
    {"question": "What was the organic revenue growth for the Big 3 for the nine months 2025?", "answer": "+9%"},
    {"question": "How many editorial enhancements does Westlaw leverage to identify legal issues?", "answer": "36 million"},
    {"question": "What does Westlaw identify using the 36 million editorial enhancements?", "answer": "legal issues including case law Headnotes and Key Numbers"},
    {"question": "What does Westlaw determine during query analysis and planning?", "answer": "jurisdictions"},
    {"question": "What does Westlaw create in Step 1 of the process?", "answer": "research plan"},
    {"question": "How many state and federal cases does Westlaw search?", "answer": "14.7 million"},
    {"question": "How many current statutes and regulations does Westlaw search?", "answer": "4.7 million"},
    {"question": "How many federal and state administrative decisions does Westlaw search?", "answer": "39 million"},
    {"question": "How many texts, treatises, and encyclopedias does Westlaw search?", "answer": "1,900"},
    {"question": "How many legal classifications are in the West Key Number System?", "answer": "35 million"},
    {"question": "How many Precision Research attributes does Westlaw leverage?", "answer": "3.9 million"},
    {"question": "How many statutes and regulations annotations does Westlaw explore connections with?", "answer": "22.5 million"},
    {"question": "How many KeyCite connections does Westlaw cross-reference during refinement?", "answer": "1.4 billion"},
    {"question": "What does Westlaw update in Step 4?", "answer": "research plan"},
    {"question": "What does Westlaw complete in Step 4?", "answer": "issue research"},
    {"question": "How many validity signals does KeyCite use to confirm the law is still valid?", "answer": "68 million"},
    {"question": "Which system does Westlaw use to identify cases on both sides of an issue?", "answer": "West Key Number System and KeyCite relationships"},
    {"question": "How many Practical Law guides does Westlaw include during validation?", "answer": "113,000"},
    {"question": "How many Westlaw documents are used to verify the report?", "answer": "68.5 million"},
    {"question": "What does Westlaw deliver in Step 6?", "answer": "final report"},
    {"question": "What is produced as part of the initial output in Step 6?", "answer": "initial report"},
    {"question": "How many years of editorially-enhanced US case law does Westlaw have?", "answer": "100+ years"},
    {"question": "How many documents are in the Westlaw database?", "answer": "1.9 billion"},
    {"question": "How many documents does Westlaw process annually?", "answer": "300 million"},
    {"question": "How many sources contribute to Westlaw's annual document processing?", "answer": "3,500+"},
    {"question": "How many state and federal cases does Westlaw include?", "answer": "14.7 million"},
    {"question": "How many federal and state administrative decisions does Westlaw include?", "answer": "39 million"},
    {"question": "How many current statutes and regulations does Westlaw include?", "answer": "4.7 million"},
    {"question": "How many historical statutes and regulations does Westlaw include?", "answer": "100+ million"},
    {"question": "How many texts, treatises, and encyclopedias does Westlaw include?", "answer": "2,200+"},
    {"question": "How many Practical Law documents does Westlaw provide?", "answer": "113,000+"},
    {"question": "Which key brands are included in Practical Law & secondary sources?", "answer": "Rutter, Witkin, McCarthy on Trademarks"},
    {"question": "How many new editorial enhancements does Westlaw produce per year?", "answer": "1.6 million"},
    {"question": "How many Legal Attorney Editors does Westlaw have?", "answer": "1,500+"},
    {"question": "How many classifications are in the West Key Number System?", "answer": "35 million"},
    {"question": "How many Precision Research attributes are tagged to case law?", "answer": "3.9 million"},
    {"question": "How many editorial enhancements such as headnotes and synopses has Westlaw created?", "answer": "36 million"},
    {"question": "How many statutes and regulations annotations does Westlaw have?", "answer": "22.5 million"},
    {"question": "How many connections exist in the KeyCite relationship network?", "answer": "1.4 billion"},
    {"question": "How many documents have KeyCite capabilities?", "answer": "68 million"},
    {"question": "What is the only citator that flags cases overruled in part?", "answer": "KeyCite"}
]
